from datetime import datetime
from typing import Protocol
from uuid import UUID

from ..domain.entities import User


class UserRepository(Protocol):
    async def create(self, *, name: str, email: str, password_hash: str,
                     latitude: float | None, longitude: float | None) -> User: ...

    async def find_credentials_by_email(self, email: str) -> tuple[User, str] | None: ...

    async def find_by_id(self, user_id: UUID) -> User | None: ...

    async def update_location(self, user_id: UUID, **values) -> None: ...

    async def update_alert_preferences(self, user_id: UUID, **values) -> None: ...

    async def anonymize(self, user_id: UUID) -> bool: ...


class RevokedTokenRepository(Protocol):
    async def revoke(self, *, jti: UUID, user_id: UUID, expires_at: datetime) -> None: ...

    async def is_revoked(self, jti: UUID) -> bool: ...
